App_ControleDeFuncionarios/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace App_ControleDeFuncionarios.Models
{
    public class Funcionario
    {

        [Key]
        public int Id { get; set; }

        [DisplayName("Mátricula")]
        [Required(ErrorMessage = "É obrigatório informar {0}")]
        public int Matricula { get; set; }

        [Required(ErrorMessage = "É obrigatório informar {0}")]
        [MaxLength(50, ErrorMessage = "No máximo 50 caracteres")]
        public string Nome { get; set; }

        [MaxLength(50, ErrorMessage = "No máximo 50 caracteres")]
        public string Sobrenome { get; set; }

        [DisplayName("E-mail")]
        [Required(ErrorMessage = "É obrigatório informar {0}")]
        [EmailAddress(ErrorMessage = "{0} em formato inválido")]
        public string Email { get; set; }

        public bool Ativo { get; set; }

        [DisplayName("Data de admissão")]
        [Required(ErrorMessage = "É obrigatório informar {0}")]
        public DateTime DataAdmissao { get; set; }

        [DisplayName("Data de demissão")]
        public DateTime? DataDemissao { get; set; }

    }
}

App_ControleDeFuncionarios/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using App_ControleDeFuncionarios.Models;

namespace App_ControleDeFuncionarios.Controllers
{
    [Authorize]
    public class FuncionariosController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        
        [HttpGet]
        [Route("listar-funcionarios")]
        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            return View(await db.Funcionarios.ToListAsync());
        }

        [HttpGet]
        [Route("funcionario-detalhe/{id:int}")]
        public async Task<ActionResult> Details(int id)
        {            
            var funcionario = await db.Funcionarios.FindAsync(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            
            return View(funcionario);
        }

        [HttpGet]
        [Route("novo-funcionario")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("novo-funcionario")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Matricula,Nome,Sobrenome,Email,Ativo,DataAdmissao,DataDemissao")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                db.Funcionarios.Add(funcionario);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(funcionario);
        }

        [HttpGet]
        [Route("editar-funcionario/{id:int}")]
        public async Task<ActionResult> Edit(int id)
        {          
            var funcionario = await db.Funcionarios.FindAsync(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        [HttpPost]
        [Route("editar-funcionario/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Matricula,Nome,Sobrenome,Email,Ativo,DataAdmissao,DataDemissao")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(funcionario).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        [HttpGet]
        [Route("excluir-funcionario/{id:int}")]
        public async Task<ActionResult> Delete(int id)
        {           
            var funcionario = await db.Funcionarios.FindAsync(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        [HttpPost]
        [Route("excluir-funcionario/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var funcionario = await db.Funcionarios.FindAsync(id);
            db.Funcionarios.Remove(funcionario);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App_ControleDeFuncionarios/Views/Funcionarios/Create.cshtml
@model App_ControleDeFuncionarios.Models.Funcionario

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataAdmissao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataAdmissao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataAdmissao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDemissao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDemissao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDemissao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirmar" class="btn btn-success" />
                <a href="@Url.Action("Index", "Funcionarios")" class="btn btn-default">Voltar</a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App_ControleDeFuncionarios/Views/Funcionarios/Delete.cshtml
@model App_ControleDeFuncionarios.Models.Funcionario

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Você tem certeza que quer prosseguir?</h3>
<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataAdmissao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAdmissao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDemissao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDemissao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Confirmar" class="btn btn-danger" />
            <a href="@Url.Action("Index", "Funcionarios")" class="btn btn-default">Voltar</a>
        </div>
    }
</div>

App_ControleDeFuncionarios/Views/Funcionarios/Details.cshtml
@model App_ControleDeFuncionarios.Models.Funcionario

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataAdmissao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAdmissao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDemissao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDemissao)
        </dd>

    </dl>
</div>
<p>    
    <a href="@Url.Action("Edit", "Funcionarios")" class="btn btn-warning">Editar</a>
    <a href="@Url.Action("Index", "Funcionarios")" class="btn btn-default">Voltar</a>
</p>

App_ControleDeFuncionarios/Views/Funcionarios/Edit.cshtml
@model App_ControleDeFuncionarios.Models.Funcionario

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataAdmissao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataAdmissao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataAdmissao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDemissao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDemissao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDemissao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirmar" class="btn btn-success" />
                <a href="@Url.Action("Index", "Funcionarios")" class="btn btn-default">Voltar</a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App_ControleDeFuncionarios/Views/Funcionarios/Index.cshtml
@model IEnumerable<App_ControleDeFuncionarios.Models.Funcionario>

@{
    ViewBag.Title = "Listagem";
}

<h2>Listagem</h2>

<div>
    <a href="@Url.Action("Create")" class="btn btn-primary">Cadastrar</a><br /><br />
</div>

<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th>            
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sobrenome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ativo)
        </td>
        <td>
            <a href="@Url.Action("Edit", "Funcionarios", new { id = item.Id })" class="btn btn-warning">Editar</a>
            <a href="@Url.Action("Details", "Funcionarios", new { id = item.Id })" class="btn btn-info">Detalhes</a>
            <a href="@Url.Action("Delete", "Funcionarios", new { id = item.Id })" class="btn btn-danger">Deletar</a>            
        </td>
    </tr>
}

</table>